# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2881872d689ee385abe4f5cefe4aaf2cfe9637eac9aa0412668f8eaa37f5a04dfb4d2f0789b60c3640f8a3d9987ffc224ef7094c9c226511895c55fc7f2eb7b6

test:
  secret_key_base: 334e5ee91cce54d053964efdbc27a1fd30815a588f52b26f30e2723ed2306367b32cb55e31643681fac9826d64d6b62d9a6b2bbffe063afc04422df94f589bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
